services:

  postgres:

    image: postgres:latest

    restart: always

    environment:

      - POSTGRES_USER=imrul

      - POSTGRES_PASSWORD=asdf

    volumes:

      - postgres:/var/lib/postgresql/ticketing-service

    ports:

      - '5432:5432'


volumes:

  postgres: